### ISSUE TITLE
Support Game By Python Programming

### ISSUE THREAD

**Issue by kevin-gutenberg** [kevin-gutenberg/FlappyBird#1]
I'm a newbie in Python. I'm coding a game Flappy Bird by pygame library. I have finished GUI for this game and create feature check collision between the bird and the tube. But I can't create feature to check when the bird pass through the tube.

I want the score will increase when the bird pass the tube.
![image](https://user-images.githubusercontent.com/118275191/202084387-1d18530b-531e-4f3c-9fa9-b2b22cc38708.png)
The score will show 1, 2, 3, 4, 5, ....

**Comment by duonghuynhnhan** [comment]
Hi bro, with my ability, I think I can help you create this feature.

**Comment by duonghuynhnhan** [comment]
May you assign it to me?

**Comment by kevin-gutenberg** [comment]
Ok, duonghuynhnhan

**Comment by kevin-gutenberg** [comment]
Thank you very much bro, duonghuynhnhan. Great
